#!/bin/sh

# Exit immediately if any command fails
set -e

echo "Running pre-push checks..."

echo "-> Running cargo check"
cargo check

echo "-> Running cargo clippy"
cargo clippy -- -D warnings

echo "-> Running cargo test"
cargo test
