#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Action {
    GoToTopUI,
    GoToBottomUI,
    AppendCharacter(char),
    RemoveCharacter,
    EnterCommandMode,
    EnterInsertMode,
    EnterInsertModeAfter,
    EnterInsertModeLineStart,
    EnterInsertModeLineEnd,
    OpenNewLineBelow,
    OpenNewLineAbove,
    DeleteLine,
    Enter,
    CursorLeft,
    CursorRight,
    CursorUp,
    CursorDown,
    Escape,
    Quit,
}
